name: jaspr_svg
description: Svg for Jaspr -- From assets and from data URL
version: 0.1.0+1
repository: https://github.com/FlutterPlaza/jasprfire/tree/main/packages/jaspr_svg
homepage: https://www.flutterplaza.com/


environment:
  sdk: ^3.4.0

dependencies:
  universal_io: ^2.2.2
  jaspr: ^0.19.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
